version: '2'
services:
  minio:
    image: minio/minio
    volumes:
      - './data:/data'
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: F6WUUG27HBUFSIXVZL59
      MINIO_SECRET_KEY: BPlIUU6SX0ZxiCMo3tIpCMAUdnmkN9Eo9K42NsRR
    command: server /data
  upload-service:
    image: upload-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      S3_ACCESS_KEY: F6WUUG27HBUFSIXVZL59
      S3_SECRET_KEY: BPlIUU6SX0ZxiCMo3tIpCMAUdnmkN9Eo9K42NsRR
      S3_ENDPOINT: http://minio:9000
    ports:
      - 8080:8080
    depends_on:
      - minio
